[build]
  publish = "dist"
  command = "yarn build"

# [[redirects]]
#   from = "https://gridsome-starter-site.netlify.com/*"
#   to = "https://gridsome-starter-site.nakamu.life/:splat"
#   force = true